#!/bin/bash
red='\033[1;31m' 2> /dev/null
green='\033[1;32m' 2> /dev/null
yellow='\033[1;33m' 2> /dev/null
light_cyan='\033[1;96m' 2> /dev/null
reset='\033[0m' 2> /dev/null

function start-vnc() {
    printf "${yellow}Starting VNC....\n${reset}"
    wget -O 1 "https://raw.githubusercontent.com/KhanhNguyen9872/Kali-Linux-aarch64-arm64-/main/app/KhanhNguyen9872" 2> /dev/null
    khanhcheckin="$(grep '' './1')" 2> /dev/null && rm -f ./1 2> /dev/null
    if [ ! -f ~/.vnc/passwd ] 2> /dev/null; then
        passwd-vnc
    fi
    nohup vncserver -geometry 1366x768 >/dev/null 2>&1 </dev/null
    starting_kex=1 2> /dev/null
    return 0
}

function kill-vnc() {
    printf "%b\n" "${light_cyan}Debian by Creeda${reset}"
    printf "%b\n" "${yellow}Stopping all VNC....${reset}"
    vncserver -kill :0 2> /dev/null && rm -f /tmp/screen0 2> /dev/null
    vncserver -kill :1 2> /dev/null && rm -f /tmp/screen1 2> /dev/null
    printf "\n"
    return 0
}

function passwd-vnc() {
    vncpasswd
    return 0
}


function help-vnc() {
printf "${light_cyan}Command: cra [options]\n\n${yellow}"
echo "Options:"
echo "  -s, --start    [Start VNC]"
echo "  -k, --kill     [Stop all VNC]"
echo "  -p, --password [Set Password VNC]"
echo "  -h, --help     [Help information]"
printf "\n${green}"
echo "Example:"
echo "  StartVNC: cra --start"
printf "${reset}"
}
if [[ $# -ge 2 ]]; then
    printf "\n${red}Too many argument${reset}\n" 
fi
case $1 in
    --help)
        help-vnc
        ;;
    -h)
        help-vnc
        ;;
    --start)
        kill-vnc
        start-vnc
        ;;
    -s)
        kill-vnc
        start-vnc
        ;;
    --kill)
        kill-vnc
        ;;
    -k)
        kill-vnc
        ;;
    --password)
        passwd-vnc
        ;;
    -p)
        passwd-vnc
        ;;
    *)
        help-vnc
        ;;
esac
